collections_config:
  pages:
    name: Pages
    path: ''
  posts:
    name: Posts
    path: posts
    filter:
      exclude:
        - newpost.js.md
        - test.md
collection_groups:
  - heading: Content
    collections:
      - pages
      - posts
paths:
  static: ''
  uploads: uploads
_inputs:
  template:
    hidden: true
